// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkBO73M4rdSVpGew4g4fJmKC0salDfYxc',
    appId: '1:996789439098:web:2519a9ef1c7caa962349c3',
    messagingSenderId: '996789439098',
    projectId: 'actual-loginui',
    authDomain: 'actual-loginui.firebaseapp.com',
    storageBucket: 'actual-loginui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXPQQGX8OWcSEgLRgqCOVVPWZfTf-fqWI',
    appId: '1:996789439098:android:b71858238f12d4332349c3',
    messagingSenderId: '996789439098',
    projectId: 'actual-loginui',
    storageBucket: 'actual-loginui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr4CTNKGst0XXWmhxGlhcpobLb_JH84ZI',
    appId: '1:996789439098:ios:ad7f2c0d3c9edf7b2349c3',
    messagingSenderId: '996789439098',
    projectId: 'actual-loginui',
    storageBucket: 'actual-loginui.appspot.com',
    iosClientId: '996789439098-vm8blj1g75behnfj175en9a827s61t8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr4CTNKGst0XXWmhxGlhcpobLb_JH84ZI',
    appId: '1:996789439098:ios:ad7f2c0d3c9edf7b2349c3',
    messagingSenderId: '996789439098',
    projectId: 'actual-loginui',
    storageBucket: 'actual-loginui.appspot.com',
    iosClientId: '996789439098-vm8blj1g75behnfj175en9a827s61t8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );
}
